name       : antimicro
version    : 2.23
release    : 5
source     :
    - https://github.com/AntiMicro/antimicro/archive/2.23.tar.gz : ef309170612da805992f9194f1973bf38a3174a0856856afedab67f9d927a9ef
license    : GPL-3.0
component  : games
summary    : antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad.
description: |
    antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xtst)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
