name       : antimicro
version    : 2.21
release    : 4
source     :
    - https://github.com/AntiMicro/antimicro/archive/2.21.tar.gz : 2a361410d184341ca325a535e212325f75fc244a331a7062eb057067295f05ba
license    : GPL-3.0
component  : games
summary    : antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad.
description: |
    antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xtst)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
